kind: Secret
apiVersion: v1
metadata:
  name: product-secret
  namespace: kube-micro
type: Opaque
data:
  DATABASE_URL: cG9zdGdyZXNxbDovL3Bvc3RncmVzOkFkbWluQHBvc3RncmVzLXNlcnZpY2U6NTQzMi9hcHA=
  SECRET_KEY: bXlzZWNyZXRrZXk=
  JWT_SECRET_KEY: OWY0ZDZiM2U4YTdjNWQyZjFlOWI0YTZjN2Q4ZTlmMTIzNDU2Nzg5MGFiY2RlZjEyMzQ1Njc4OTBhYmNkZWY=