kind: Deployment
apiVersion: apps/v1
metadata:
  name: product-deployment
  namespace: kube-micro
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
        - name: product-pod
          image: ankit8779/product-service
          ports:
            - containerPort: 5001
          env:
            env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: product-secret
                  key: DATABASE_URL
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: product-secret
                  key: SECRET_KEY
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: product-secret
                  key: JWT_SECRET_KEY