kind: Secret
apiVersion: v1
metadata:
  name: auth-secret
  namespace: kube-micro
type: Opaque
data:
  DATABASE_URL: cG9zdGdyZXNxbDovL3Bvc3RncmVzOkFkbWluQGxvY2FsaG9zdDo1NDMyL2FwcA==
  SECRET_KEY: bXlzZWNyZXRrZXk=
  JWT_SECRET_KEY: OWY0ZDZiM2U4YTdjNWQyZjFlOWI0YTZjN2Q4ZTlmMTIzNDU2Nzg5MGFiY2RlZjEyMzQ1Njc4OTBhYmNkZWY=