apiVersion: batch/v1
kind: Job
metadata:
  name: auth-migrations
  namespace: kube-micro
spec:
  template:
    spec:
      containers:
      - name: migrate
        image: ankit8779/auth-service:latest
        command: ["flask", "db", "upgrade"]
        env:
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: auth-secret
                key: DATABASE_URL
          - name: SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: auth-secret
                key: SECRET_KEY
          - name: JWT_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: auth-secret
                key: JWT_SECRET_KEY
      restartPolicy: Never
